# huggingface Amazon clothing data 수집
https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023

In [ ]:
from huggingface_hub import list_repo_files

repo_id = "McAuley-Lab/Amazon-Reviews-2023"
files = list_repo_files(repo_id, repo_type="dataset")

fashion_files = [f for f in files if "Clothing" in f or "Fashion" in f]


for f in fashion_files:
    print(f)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

benchmark/0core/last_out/Amazon_Fashion.test.csv
benchmark/0core/last_out/Amazon_Fashion.train.csv
benchmark/0core/last_out/Amazon_Fashion.valid.csv
benchmark/0core/last_out/Clothing_Shoes_and_Jewelry.test.csv
benchmark/0core/last_out/Clothing_Shoes_and_Jewelry.train.csv
benchmark/0core/last_out/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/0core/last_out_w_his/Amazon_Fashion.test.csv
benchmark/0core/last_out_w_his/Amazon_Fashion.train.csv
benchmark/0core/last_out_w_his/Amazon_Fashion.valid.csv
benchmark/0core/last_out_w_his/Clothing_Shoes_and_Jewelry.test.csv
benchmark/0core/last_out_w_his/Clothing_Shoes_and_Jewelry.train.csv
benchmark/0core/last_out_w_his/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/0core/rating_only/Amazon_Fashion.csv
benchmark/0core/rating_only/Clothing_Shoes_and_Jewelry.csv
benchmark/0core/timestamp/Amazon_Fashion.test.csv
benchmark/0core/timestamp/Amazon_Fashion.train.csv
benchmark/0core/timestamp/Amazon_Fashion.valid.csv
benchmark/0core/timestamp/Clothing_Shoes_and_Jewelry.test.csv
benchmark/0core/timestamp/Clothing_Shoes_and_Jewelry.train.csv
benchmark/0core/timestamp/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/0core/timestamp_w_his/Amazon_Fashion.test.csv
benchmark/0core/timestamp_w_his/Amazon_Fashion.train.csv
benchmark/0core/timestamp_w_his/Amazon_Fashion.valid.csv
benchmark/0core/timestamp_w_his/Clothing_Shoes_and_Jewelry.test.csv
benchmark/0core/timestamp_w_his/Clothing_Shoes_and_Jewelry.train.csv
benchmark/0core/timestamp_w_his/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/5core/last_out/Clothing_Shoes_and_Jewelry.test.csv
benchmark/5core/last_out/Clothing_Shoes_and_Jewelry.train.csv
benchmark/5core/last_out/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/5core/last_out_w_his/Clothing_Shoes_and_Jewelry.test.csv
benchmark/5core/last_out_w_his/Clothing_Shoes_and_Jewelry.train.csv
benchmark/5core/last_out_w_his/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/5core/rating_only/Clothing_Shoes_and_Jewelry.csv
benchmark/5core/timestamp/Clothing_Shoes_and_Jewelry.test.csv
benchmark/5core/timestamp/Clothing_Shoes_and_Jewelry.train.csv
benchmark/5core/timestamp/Clothing_Shoes_and_Jewelry.valid.csv
benchmark/5core/timestamp_w_his/Clothing_Shoes_and_Jewelry.test.csv
benchmark/5core/timestamp_w_his/Clothing_Shoes_and_Jewelry.train.csv
benchmark/5core/timestamp_w_his/Clothing_Shoes_and_Jewelry.valid.csv
raw/meta_categories/meta_Amazon_Fashion.jsonl
raw/meta_categories/meta_Clothing_Shoes_and_Jewelry.jsonl
raw/review_categories/Amazon_Fashion.jsonl
raw/review_categories/Clothing_Shoes_and_Jewelry.jsonl

In [ ]:
import pandas as pd


base_url = "https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/"
file_path = "raw/review_categories/Amazon_Fashion.jsonl"
url = base_url + file_path

try:
    df_sample = pd.read_json(url, lines=True, nrows=100)

    print("데이터 로드 완료.")
    display(df_sample[['rating', 'title', 'text']].head(10))

    print("\n[상세 리뷰 샘플 (상위 10개)]")
    print(df_sample['text'].iloc[10])

except Exception as e:
    print(f"로드 실패 (에러 메시지 확인): {e}")

데이터 로드 완료.

,rating,title,text
0,5,Pretty locket,I think this locket is really pretty. The insi...
1,5,A,Great
2,2,Two Stars,One of the stones fell out within the first 2 ...
3,1,Won’t buy again,Crappy socks. Money wasted. Bought to wear wit...
4,5,I LOVE these glasses,I LOVE these glasses! They fit perfectly over...
5,3,Adult friendly; Not for small kids,Works OK for adults and is not at all kid frie...
6,5,Five Stars,Great fit
7,4,Heavy earrings for size of owls but so darn cute!,Would be five stars but they are just too heav...
8,5,Bright and summer,What a cute top! Cam wait to wear in warm weat...
9,2,Scratchy,"Very inexpensive, but too rough and uncomforta..."

[상세 리뷰 샘플 (상위 10개)]
Runs way smaller than indicated.

In [ ]:
# 평점이 2점 이하인 리뷰만 추출
low_rating_df = df_sample[df_sample['rating'] <= 2]

print(f"필터링된 리뷰 개수: {len(low_rating_df)}")
display(low_rating_df[['rating', 'text']].head(10))

# 이 리뷰들에서 가장 많이 나온 단어 확인
from collections import Counter
all_text = " ".join(low_rating_df['text'].tolist()).lower()
words = all_text.split()
common_words = Counter(words).most_common(20)
print("\n[부정 리뷰 주요 키워드]\n", common_words)

필터링된 리뷰 개수: 16

    rating                                               text
2        2  One of the stones fell out within the first 2 ...
3        1  Crappy socks. Money wasted. Bought to wear wit...
9        2  Very inexpensive, but too rough and uncomforta...
10       2                   Runs way smaller than indicated.
12       2  There are lots of raw edges.  Not well made.  ...
25       1  Hat arrived without piece that secured and adj...
40       2  The lenses pop out occasionally, not a fashion...
43       1  Run VERY small , cheap material and not slit u...
48       2  Well.  I really like the idea, however, they a...
49       2  I am 5'7".. usually wear a 14/16 or 0x/1x.. 38...

[부정 리뷰 주요 키워드]
 [('the', 58), ('i', 41), ('a', 29), ('to', 24), ('and', 22), ('-', 16), ('not', 15), ('are', 14), ('is', 14), ('it', 12), ('of', 10), ('but', 10), ('they', 10), ('you', 10), ('if', 10), ('have', 9), ('this', 9), ('that', 9), ('so', 9), ('just', 9)]

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
filtered_words = [w for w in words if not w in stop_words and len(w) > 1]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!